version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-aspnetcore-runtime
    steps:
      - checkout
      - run: find .
      - run: dotnet build "SEContactManager.UI.Web.csproj" -c Release -o /app
