version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build
    steps:
      - checkout
      - run:
          name: Building the project
          name: Moving to the project directory
          command: |
            pushd ./src/SEContactManager.UI.Web
            dotnet build "SEContactManager.UI.Web.csproj" -c Release -o /app
            popd
      - run:
          name: Run result
          command: dotnet out/SEContactManager.UI.Web.dll

