version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet build "./src/SEContactManager.UI.Web.sln" -c Release -o /app
