version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.300-preview2-sdk-alpine
    steps:
      - checkout
      - run: find .
      - run: dotnet restore "./src/SEContactManager.UI.Web.sln"
      - run: dotnet build "SEContactManager.UI.Web.sln" -c Release -o /app
